// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.tansadio.monmp3.Mp3;

public interface _LecteurMp3Operations
{
    String jouer(Ice.Current __current);

    String pause(Ice.Current __current);

    void stop(Ice.Current __current);

    void selectedMusic(String name, Ice.Current __current);

    String[] getFilemp3(Ice.Current __current);
}
