// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.tansadio.monmp3.Mp3;

public final class LecteurMp3PrxHolder
{
    public
    LecteurMp3PrxHolder()
    {
    }

    public
    LecteurMp3PrxHolder(LecteurMp3Prx value)
    {
        this.value = value;
    }

    public LecteurMp3Prx value;
}
