// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.tansadio.monmp3.Mp3;

public final class LecteurMp3Holder extends Ice.ObjectHolderBase<LecteurMp3>
{
    public
    LecteurMp3Holder()
    {
    }

    public
    LecteurMp3Holder(LecteurMp3 value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof LecteurMp3)
        {
            value = (LecteurMp3)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _LecteurMp3Disp.ice_staticId();
    }
}
